[workspace]
members = [
    'runtime/moonbeam',
    'runtime/moonriver',
    'runtime/moonbase',
    'node',
    'node/cli',
    'node/service',
    'pallets/migrations',
    'pallets/proxy-genesis-companion',
    'bin/utils/moonkey',
    'pallets/maintenance-mode',
    'precompiles/utils/macro',
    'client/rpc/manual-xcm',
]
exclude = [
    'bin/utils/moonkey'
]

[profile.release]
panic = 'unwind'

[patch.crates-io]
evm = { git = "https://github.com/purestake/evm", branch = "moonbeam-polkadot-v0.9.11"}
evm-runtime = { git = "https://github.com/purestake/evm", branch = "moonbeam-polkadot-v0.9.11" }
evm-gasometer = { git = "https://github.com/purestake/evm", branch = "moonbeam-polkadot-v0.9.11" }
ethereum = { git = "https://github.com/purestake/ethereum", branch = "joshy-scale-info" }

# Patches for individual cumulus crates that I want to override while working on mock xcm
[patch."https://github.com/purestake/cumulus"]
cumulus-primitives-parachain-inherent = { git = "https://github.com/joshorndorff/cumulus", branch = "moonbeam-polkadot-v0.9.11" }
cumulus-pallet-parachain-system = { git = "https://github.com/joshorndorff/cumulus", branch = "moonbeam-polkadot-v0.9.11" }